name: Build

on: 
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update & sudo apt upgrade -y
      - run: sudo apt-get install -y autotools-dev gcc make
      - run: autoreconf --install
      - run: ./configure
      - run: make  

