name: build

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y autotools-dev autoconf-archive gcc make guile-3.0-dev
      - run: autoreconf --install
      - run: ./configure
      - run: make
