name: Compile

on: 
  push:
    branches:
      - main
      - development

jobs:
  install-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y autotools-dev gcc make
      - run: gcc --version  

